# .github/workflows/ci.yml

name: Lua Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository's code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Lua and Luarocks
      # We explicitly request Luarocks to ensure it is installed and its path
      # is correctly exported for subsequent steps.
      - name: Set up Lua
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.1"

      - name: Set up Luarocks
        uses: leafo/gh-actions-luarocks@v4

      # Step 3: Install dependencies
      # We install busted and penlight. The `--local` flag is good practice
      # as it installs them into a user-local directory without needing sudo.
      # The setup actions will ensure the PATH is configured to find these.
      - name: Install dependencies
        run: luarocks install --local busted penlight

      # Step 4: Run the tests
      # This step will now be able to find the `busted` executable.
      - name: Run tests
        run: busted specs/*