# .github/workflows/ci.yml

name: Lua Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository's code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Lua and Luarocks
      # We explicitly request Luarocks to ensure it is installed and its path
      # is correctly exported for subsequent steps.
      - name: Set up Lua
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.4"
          luarocksVersion: "latest" # Be explicit about installing Luarocks

      # Step 3: Install dependencies using separate, atomic steps.
      # This is the key fix. Each 'run' command executes in a new shell
      # that correctly inherits the updated PATH from the 'Set up Lua' step.
      - name: Install Busted
        run: luarocks install busted

      - name: Install Penlight
        run: luarocks install penlight

      # Step 4: Run the tests
      # This step will now be able to find the `busted` executable.
      - name: Run tests
        run: busted specs/*